In [269]:
import numpy as np

In [270]:
def f(x):
    return x


def grad(x):
    return 1


def hess(x):
    return np.array([0])


In [271]:
A = np.array([[1], [-1]])
b = np.array([[0], [-1]])

x0 = 0.8
lam0 = np.array([[0.1], [0.1]])
m = 2

alpha = 0.2
sigma = 0.2



In [272]:
#calcular y
y = A*x0-b
y

array([[0.8],
       [0.2]])

In [273]:
#calcular mu
print(lam0)
print(y)
mu = np.dot(y.T, lam0)/m
mu

[[0.1]
 [0.1]]
[[0.8]
 [0.2]]


array([[0.05]])

In [274]:
#poblar Y
Y = np.zeros((m,m))
# print(Y)
for i in range(len(Y)):
    Y[i,i] = y[i]
Y


array([[0.8, 0. ],
       [0. , 0.2]])

In [275]:
# poblar Lamda
L = np.zeros((m, m))
# print(L)
for i in range(len(L)):
    L[i, i] = lam0[i]
L
# print(np.linalg.inv(L))


array([[0.1, 0. ],
       [0. , 0.1]])

In [276]:
#valores de rd 
rd = grad(x0) - np.dot(A.T,lam0)
rd


array([[1.]])

In [277]:
#valores de rb
e = np.ones((2))
aux = np.dot(np.linalg.inv(L),e)
rb = y.T-sigma*mu*aux
print(rb)


[[0.7 0.1]]


In [278]:

mA = -A.T
mA=np.append(hess(0), mA)
print(mA)
mB = np.array([A])
c = np.dot(np.linalg.inv(L), Y)
c

mB = np.concatenate((A, c), axis=1)
mB
sistema=np.vstack((mA, mB))
print(sistema)



[ 0 -1  1]
[[ 0. -1.  1.]
 [ 1.  8.  0.]
 [-1.  0.  2.]]


In [279]:
# print(L.dot(e))
igualdades = np.array([grad(x0)])
igualdades = np.append(-igualdades,-rb)
print(igualdades)

[-1.  -0.7 -0.1]


In [280]:
np.linalg.solve(sistema,igualdades)

array([-1.66,  0.12, -0.88])