In [1]:
import numpy as np

In [89]:
def f(x):
    return x


def grad(x):
    return 1


def hess(x):
    return np.array([0])


In [90]:
A = np.array([[1], [-1]])
b = np.array([[0], [-1]])

x0 = np.array([0.8])
lam0 = np.array([0.1,0.1])
# m = 2
m = A.shape[0]
n = x0.shape[0]

alpha = 0.2
sigma = 0.2



In [91]:
#calcular y
y = A*x0-b
y

array([[0.8],
       [0.2]])

In [92]:
#calcular mu
print(lam0)
print(y)
mu = np.dot(y.T, lam0)/m
mu

[0.1 0.1]
[[0.8]
 [0.2]]


array([0.05])

In [93]:
#poblar Y
Y = np.zeros((m,m))
for i in range(len(Y)):
    Y[i,i] = y[i]
Y


array([[0.8, 0. ],
       [0. , 0.2]])

In [94]:
# poblar Lamda
L = np.zeros((m, m))
# print(L)
for i in range(len(L)):
    L[i, i] = lam0[i]
L
# print(np.linalg.inv(L))


array([[0.1, 0. ],
       [0. , 0.1]])

In [95]:
#valores de rd 
rd = grad(x0) - np.dot(A.T,lam0)
rd


array([1.])

In [96]:
#valores de rb
e = np.ones((2))
aux = np.dot(np.linalg.inv(L),e)
rb = y.T-sigma*mu*aux
print(rb)


[[0.7 0.1]]


In [97]:

mA = -A.T
mA=np.append(hess(0), mA)
print(mA)
mB = np.array([A])
c = np.dot(np.linalg.inv(L), Y)
c

mB = np.concatenate((A, c), axis=1)
mB
sistema=np.vstack((mA, mB))
print(sistema)



[ 0 -1  1]
[[ 0. -1.  1.]
 [ 1.  8.  0.]
 [-1.  0.  2.]]


In [98]:
# print(L.dot(e))
igualdades = np.array([grad(x0)])
igualdades = np.append(-igualdades,-rb)
print(igualdades)

[-1.  -0.7 -0.1]


In [99]:
deltas = np.linalg.solve(sistema,igualdades)
# print(deltas)
# actualizamos x y lamda

x0 = x0 + alpha*deltas[:n]
lam0 = lam0+ alpha*deltas[n:]

y = A*x0 - b

In [12]:
def puntoInterior(x0, lam0, A, b, alpha=0.2, sigma=0.2):
    k = 0
    n = x0.shape[0]
    m = A.shape[0]
    
    y = A.dot(x0)-b
    print("k, lamdas, x, y, error")
   
    for i in range (0,1000):
       
        rd = grad(x0) - np.dot(A.T, lam0)
        mu = np.dot(y.T, lam0)/m
        # print(rd, mu)

        # llenar Y
        Y = np.zeros((m, m))
        for i in range(len(Y)):
            Y[i, i] = y[i]
        # llenar Lamda
        L = np.zeros((m, m))
        for i in range(len(L)):
            L[i, i] = lam0[i]
        # valores de rb
        e = np.ones((m))
        aux = np.dot(np.linalg.inv(L), e)
        rb = y.T-sigma*mu*aux
        # print(rb)

        
        F = np.array([rd])
        F = np.append(-F, -rb)
        # print(F)

        mA = np.concatenate((hess(x0), -A.T), axis=1)
        # print(mA)
        mB = np.array([A])
        c = np.dot(np.linalg.inv(L), Y)
        mB = np.concatenate((A, c), axis=1)
        sistema = np.vstack((mA, mB))
        
        # print(sistema)
        deltas = np.linalg.solve(sistema, F)
        # actualizar alphas
        # print(f"nueuvo alpha : {calcularAlpha(A, x0, b, deltas, lam0)}")
        # alpha = calcularAlpha(A, x0, b, deltas, lam0)
 

        x0 = x0 + alpha*deltas[:n]
        lam0 = lam0 + alpha*deltas[n:]
        y = A.dot(x0) - b
        mDelta = np.linalg.norm(deltas)
        print(k, lam0, x0, y, mDelta)
        k += 1
        if (mDelta < 1e-6):
            return x0


def calcularAlpha(A, x, b, deltas, lam):
    m = A.shape[0]
    n = x.shape[0]

    dx = deltas[:n]
    dl = deltas[n:]

    num = b - A*x
    den = A.dot(dx)

    t1 = np.dot(num.T, num)
    t2 = np.dot(den, den)
    print(t1, t2)
    tx = t1/t2

    num1 = dl.dot(lam)
    den1 = dl.dot(dl)
    tl = -num1/den1
    print(tl)
    t = tx if tx < tl else tl
    if t > 1:
        return 1
    else:
        return t


In [101]:
A = np.array([[1], [-1]])
b = np.array([[0], [-1]])

x0 = np.array([0.8])
lam0 = np.array([0.1, 0.1])

puntoInterior(x0,lam0,A,b)

[1.] [ 0.13 -0.03]


ValueError: setting an array element with a sequence.

In [13]:
def f(x):
    return (x[0]-2)**2+(x[1]-2)**2


def grad(x):
    return np.array([2*(x[0]-2), 2*(x[1]-2)])


def hess(x):
    return np.array([[2, 0], [0, 2]])


A = np.array([
    [1, 1],
    [2, -1]
])

b = np.array([4, 0])
x0 = np.array([2, 4])
lam0 = np.array([.1, .1])

print(grad(x0))
puntoInterior(x0, lam0, A, b, 0.1, 0.2)


[0 4]
k, lamdas, x, y, error
0 [0.10210526 0.02157895] [1.93263158 3.84526316] [1.77789474 0.02      ] 1.86108269801862
1 [ 0.10318794 -0.01327934] [1.91123568 3.6878389 ] [1.59907458 0.13463246] 1.62654398782299
2 [0.1019376  0.02865221] [1.96591392 3.50844683] [1.47436075 0.42338101] 1.9217451354384716
3 [0.10225574 0.02009906] [1.96745794 3.37079894] [1.33825688 0.56411695] 1.3792238018782577
4 [0.10234579 0.01586788] [1.97264374 3.24510028] [1.21774402 0.70018719] 1.2587674865770342
5 [0.10228096 0.01336278] [1.97875253 3.13125157] [1.1100041  0.82625349] 1.1404002003623468
6 [0.10208539 0.01167339] [1.98487229 3.02843328] [1.01330557 0.9413113 ] 1.0301429098541153
7 [0.10176684 0.0104277 ] [1.99066803 2.9356784 ] [0.92634643 1.04565767] 0.9294467749231058
8 [0.10132722 0.00945002] [1.99601347 2.85203489] [0.84804835 1.13999205] 0.8382099492791062
9 [0.10076644 0.00864759] [2.00086816 2.77661244] [0.77748061 1.22512389] 0.7558486508203095
10 [0.10008393 0.0079671 ] [2.0052303  2.70

array([2.00000066, 2.00000177])

In [13]:
G = np.array([[16, 8, 4, 12],
              [8, 29, 3, 16],
              [4, 3, 102, 21],
              [12, 16, 21, 53]
              ])

d = np.array([5, -2, 10, 6])


def f(x):
    return 0.5*np.dot(x, np.dot(G, x)) - d.dot(x)


def grad(x):
    return G.dot(x)-d


def hess(x):
    return G


A = np.array([
    [1., 0., 0., 0.],
    [0., 1., 0., 0.],
    [0., 0., 1., 0.],
    [0., 0., 0., 1.],
    [-1., 0., 0., 0.],
    [0., -1., 0., 0.],
    [0., 0., -1., 0.],
    [0., 0., 0., -1.]
])
b = np.array(
    [0, 0, 0, 0, -1, -1, -1, -1]
)

# b = np.array([4, 0])
x0 = np.array([0.9, 0.9, 0.9, 0.9])
lam0 = np.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

f(x0)

# print(grad(x0))
puntoInterior(x0, lam0, A, b, 0.2, 0.2)


k, lamdas, x, y, error
0 [ 0.09419806  0.10613856  0.10037337  0.10072298 -0.00778251 -0.11524705
 -0.06336032 -0.06650681] [0.79221749 0.68475295 0.73663968 0.73349319] [0.79221749 0.68475295 0.73663968 0.73349319 0.20778251 0.31524705
 0.26336032 0.26650681] 2.3706061913102503
1 [ 0.08720674  0.11453296  0.09981635  0.10038989  0.00242384 -0.02263652
 -0.01466743 -0.01578237] [0.70439606 0.50413989 0.6044964  0.60027843] [0.70439606 0.50413989 0.6044964  0.60027843 0.29560394 0.49586011
 0.3955036  0.39972157] 1.4940407633226016
2 [ 0.08013354  0.12602383  0.09906142  0.09995551  0.00502749 -0.00944044
 -0.00507804 -0.00569898] [0.63309966 0.36221239 0.49904665 0.49363548] [0.63309966 0.36221239 0.49904665 0.49363548 0.36690034 0.63778761
 0.50095335 0.50636452] 1.0985938337489867
3 [ 0.07282493  0.14269496  0.09784628  0.09912938  0.00576547 -0.00442514
 -0.00135569 -0.00176623] [0.5757995  0.24921624 0.41472436 0.40827   ] [0.5757995  0.24921624 0.41472436 0.40827    0.4242005  0.7

array([2.78898658e-01, 3.07207498e-09, 8.36165085e-02, 1.69296397e-02])

array([ 31. ,  52.4, 107. ,  85.8])