In [172]:
import numpy as np

In [173]:
x = np.array([1,1])
lam = 1
g = np.array([2,4,-1])



uno = np.array([1,1,1])
J = np.array([
    [4-2*lam, 0, -2*x[0]],
    [0, 6-2*lam, -2*x[1]],
    [2*x[0], 2*x[1], 0]
])

def jaco (x, lam):
    return np.array([
    [4-2*lam, 0, -2*x[0]],
    [0, 6-2*lam, -2*x[1]],
    [2*x[0], 2*x[1], 0]
])

def grad (x, lam):
    return np.array([
        4*x[0] - 2*lam*x[0],
        6*x[1] - 2*lam*x[1],
        x[0]**2 + x[1]**2 -3
    ])



xalgo = uno - np.dot(np.linalg.inv(jaco(x,1)),grad(x, lam))
print(xalgo)



xnext = xalgo - np.dot(np.linalg.inv(jaco(x=[xalgo[0], xalgo[1]],lam = 3.63137769)),grad(x=[xalgo[0], xalgo[1]], lam = 3.63137769))
xnext

[1.66666667 0.83333333 2.66666667]


array([1.1796564 , 1.52402054, 1.51198759])

In [174]:
def f(x):
    # 1
    # return x[0]**2 + x[1]**2 -2
    # 2
    # return 3*x[0] + x[1] - 3
    # 3
    return x[0]**2 + x[1]**2 - 3


def grad(x):
    return np.array([
        # 1 + 2*x[-1]*x[0],
        # 1 + 2*x[-1]*x[1],
        # x[0]**2 + x[1]**2 - 2
        4*x[0] - 3*x[-1],
        6*x[1] - x[-1],
        3*x[0] + x[1] - 3

    ])


def jaco(x):
    return np.array([
        # [2*x[-1], 0, 2*x[0]],
        # [0, 2*x[-1], 2*x[1]],
        # [2*x[0], 2*x[1], 0]
        [4, 0, -3],
        [0, 6, -1],
        [3, 1, 0]
    ])


In [175]:
def newtonRaphson(xini):
    """Recibe un vector con los parametros iniciales de x y en su ultima posicion lamda
    regresa un vector con las raices de x y lamda
    """
    k = 0
    x = xini.copy()
    xk = np.zeros(x.shape)
    dif = np.allclose(xk,x)
    print(k, x, f(x))
    while not (dif):
        g = grad(x)
        j = jaco(x)
        xk = x - np.dot(np.linalg.inv(j), g)
        k = k+1
        # s = np.linalg.solve(j,-g)
        # xk = x + s
        print(k,np.around(xk,6), np.around(f(xk),6))
        dif = np.allclose(xk, x)
        x = xk
    return x


In [179]:
import time 
xini = np.array([3,2,1])

start = time.time()
root = newtonRaphson(xini)
end = time.time()
print(np.around(root, 6)) 
# print(root)
f(root)


0 [3 2 1] 10
1 [0.93103448 0.20689655 1.24137931] -2.090369
2 [0.93103448 0.20689655 1.24137931] -2.090369
[0.931034 0.206897 1.241379]


-2.0903686087990487